apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: '{{ fromSecret "acm-policies" "s3-storage-connect" "bucket" | base64dec }}'
      endpoint: s3.amazonaws.com
      insecure: false
      access_key: '{{ fromSecret "acm-policies" "s3-storage-connect" "access_key" | base64dec }}'
      secret_key: '{{ fromSecret "acm-policies" "s3-storage-connect" "secret_key" | base64dec }}'